# Generated by Django 2.0.1 on 2018-01-27 04:26

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields
import jsonfield.fields
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='competition')),
                ('modtime', models.DateTimeField(auto_now=True)),
                ('ussf_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='ussf-id')),
                ('ussf_submitted', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First (Given) Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last (Family) Name')),
                ('address1', models.CharField(help_text='Street address or PO BOX. Your player passcard will be sent to this address.', max_length=50, verbose_name='mailing address')),
                ('address2', models.CharField(blank=True, help_text='Apt, Unit, PMB, Suite, Mailbox only.', max_length=50, verbose_name='mailing address line 2')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True, verbose_name='State')),
                ('zipcode', models.CharField(blank=True, help_text='xxxxx or xxxxx-xxxx', max_length=10, null=True, verbose_name='Zip Code')),
                ('mass_id', models.CharField(blank=True, max_length=20, verbose_name='MASS ID Number')),
                ('dob', models.DateField(help_text='mm/dd/yyyy', verbose_name='Date of Birth')),
                ('country', django_countries.fields.CountryField(help_text="Country of birth is required by US Soccer for\n                        international clearance requirements by FIFA. The last item\n                        in the list is 'Not Specified'. If you chose this\n                        option, you might NOT be eligible to play in any national amateur or international\n                        competitions.", max_length=2, verbose_name='Country of Birth')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1, verbose_name='gender')),
                ('underProContract', models.BooleanField(default=False, help_text='Please check if you are under a professional soccer contract', verbose_name='Under Profesional Contract')),
                ('modtime', models.DateTimeField(auto_now=True)),
                ('ussf_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='ussf-id')),
                ('ussf_submitted', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('hook', models.CharField(choices=[('C', 'Competitions'), ('P', 'Players')], max_length=1)),
                ('body', jsonfield.fields.JSONField()),
                ('request_meta', jsonfield.fields.JSONField()),
                ('status', models.CharField(choices=[('U', 'Unprocessed'), ('P', 'Processed'), ('E', 'Error')], default='U', max_length=1)),
                ('status_message', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
